# Generated by Django 5.2.4 on 2025-07-31 16:06

import cloudinary.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50)),
                ('relation_to_PCGF2', models.CharField(blank=True, choices=[('parent', 'Parent of PCGF2'), ('affected', 'Person with PCGF2'), ('medpro', 'Medical Professional'), ('sibling', 'Sibling of PCGF2')], help_text='How user relates to PCGF2', max_length=30, null=True)),
                ('profile_photo', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('verified', models.BooleanField(default=False)),
                ('joined', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
