# Generated by Django 5.2.4 on 2025-07-29 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-time_created']},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='time',
            new_name='time_created',
        ),
    ]
